[project]
name = "ocr-ws"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "easyocr>=1.7.2",
    "rapidocr-onnxruntime>=1.4.4",
]

[project.scripts]
ocr-ws = "ocr_ws:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
